<?php

$nifty = array(
	"500470.BO"=>"500470.BO",
	"500182.BO"=>"500182.BO",
	"532977.BO"=>"532977.BO",
	"532215.BO"=>"Axis Bank Limited",
	"500180.BO"=>"HDFC Bank Limited",
	"500209.BO"=>"500209.BO",
	"524715.BO"=>"Sun Pharmaceutical Industries Limited",
	"570001.BO"=>"570001.BO",
	"500325.BO"=>"500325.BO",
	"500247.BO"=>"Kotak Mahindra Bank Limited",
	"532555.BO"=>"NTPC Limited",
	"500510.BO"=>"500510.BO",
	"500520.BO"=>"500520.BO",
	"500696.BO"=>"500696.BO",
	"500112.BO"=>"500112.BO",
	"500034.BO"=>"500034.BO",
	"532187.BO"=>"IndusInd Bank Limited",
	"500875.BO"=>"ITC Limited",
	"500820.BO"=>"Asian Paints Limited",
	"532540.BO"=>"Tata Consultancy Services Limited",
	"532898.BO"=>"Power Grid Corporation of India Limited",
	"532174.BO"=>"ICICI Bank Limited",
	"500010.BO"=>"Housing Development Finance Corporation Limited",
	"532500.BO"=>"Maruti Suzuki India Limited",
	"532454.BO"=>"Bharti Airtel Limited",
	"532755.BO"=>"TECH MAHINDRA LTD.",
	"532281.BO"=>"HCL Technologies Limited",
	"500312.BO"=>"Oil and Natural Gas Corporation Limited",
	"532648.BO"=>"Yes Bank Limited",
	"500570.BO"=>"Tata Motors Limited"
);

$sti = array(
	"S58.SI"=>"SATS Ltd.",
	"G13.SI"=>"Genting Singapore Limited",
	"BN4.SI"=>"Keppel Corporation Limited",
	"H78.SI"=>"Hongkong Land Holdings Limited",
	"U11.SI"=>"United Overseas Bank Limited",
	"S68.SI"=>"Singapore Exchange Limited",
	"Z74.SI"=>"Singapore Telecommunications Limited",
	"A17U.SI"=>"Ascendas Real Estate Investment Trust",
	"C6L.SI"=>"Singapore Airlines Limited",
	"C38U.SI"=>"CapitaLand Mall Trust",
	"U14.SI"=>"UOL Group Limited",
	"T39.SI"=>"Singapore Press Holdings Limited",
	"O39.SI"=>"Oversea-Chinese Banking Corporation Limited",
	"U96.SI"=>"Sembcorp Industries Ltd",
	"C61U.SI"=>"CapitaLand Commercial Trust",
	"C09.SI"=>"City Developments Limited",
	"F34.SI"=>"Wilmar International Limited",
	"Y92.SI"=>"Thai Beverage Public Company Limited",
	"C31.SI"=>"CapitaLand Limited",
	"D05.SI"=>"DBS Group Holdings Ltd",
	"V03.SI"=>"Venture Corporation Limited",
	"S63.SI"=>"Singapore Technologies Engineering Ltd",
	"C52.SI"=>"ComfortDelGro Corporation Limited",
	"N2IU.SI"=>"Mapletree Commercial Trust",
	"J37.SI"=>"Jardine Strategic Holdings Limited",
	"C07.SI"=>"Jardine Cycle & Carriage Limited",
	"J36.SI"=>"Jardine Matheson Holdings Limited",
	"BS6.SI"=>"Yangzijiang Shipbuilding (Holdings) Ltd.",
	"D01.SI"=>"Dairy Farm International Holdings Limited",
	"E5H.SI"=>"Golden Agri-Resources Ltd"
);

$dow30 = array(
	"HD"=>"The Home Depot, Inc.",
	"WMT"=>"Walmart Inc.",
	"MCD"=>"McDonald's Corporation",
	"UNH"=>"UnitedHealth Group Incorporated",
	"KO"=>"The Coca-Cola Company",
	"BA"=>"The Boeing Company",
	"VZ"=>"Verizon Communications Inc.",
	"AXP"=>"American Express Company",
	"JNJ"=>"Johnson & Johnson",
	"MSFT"=>"Microsoft Corporation",
	"PFE"=>"Pfizer Inc.",
	"AAPL"=>"Apple Inc.",
	"WBA"=>"Walgreens Boots Alliance, Inc.",
	"MRK"=>"Merck & Co., Inc.",
	"CVX"=>"Chevron Corporation",
	"V"=>"Visa Inc.",
	"UTX"=>"United Technologies Corporation",
	"GS"=>"The Goldman Sachs Group, Inc.",
	"NKE"=>"NIKE, Inc.",
	"PG"=>"The Procter & Gamble Company",
	"TRV"=>"The Travelers Companies, Inc.",
	"INTC"=>"Intel Corporation",
	"MMM"=>"3M Company",
	"DIS"=>"The Walt Disney Company",
	"CAT"=>"Caterpillar Inc.",
	"XOM"=>"Exxon Mobil Corporation",
	"IBM"=>"International Business Machines Corporation",
	"JPM"=>"JPMorgan Chase & Co.",
	"CSCO"=>"Cisco Systems, Inc.",
	"DOW"=>"Dow Inc."
);




?>